### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by roydekleijn** [YogiKhan/fitnesse-parallel#1]
Hello,

This seems to be  a very valuable fitnesse extension.. Can you please describe how to get this work?

Thanks,
Roy

**Comment by ykhandelwal913** [comment]
Sure Roy, I will update readme file to show how it is working.

**Comment by haroon-sheikh** [comment]
@YogiKhan did you get a chance to update README with setup instructions. It really looks like a valuable extension. Thanks.

**Comment by maikelgithub** [comment]
@YogiKhan could you please tell us how to use your project? thanks in advance

**Comment by ykhandelwal913** [comment]
i have updated the readme.. Please check and let me know if you are not able to run yet. Sorry for not having proper documentation at first place itself.

**Comment by ykhandelwal913** [comment]
This is been taken care. If you think it is still an issue. Please reopen it.
